#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Sino.Keyboard.Droid.Resource.Color.keyboard_background = global::Sample.Resource.Color.keyboard_background;
			global::Sino.Keyboard.Droid.Resource.Color.keyboard_key_frontend_color_normal = global::Sample.Resource.Color.keyboard_key_frontend_color_normal;
			global::Sino.Keyboard.Droid.Resource.Color.keyboard_key_frontend_color_pressed = global::Sample.Resource.Color.keyboard_key_frontend_color_pressed;
			global::Sino.Keyboard.Droid.Resource.Color.keyboard_key_text = global::Sample.Resource.Color.keyboard_key_text;
			global::Sino.Keyboard.Droid.Resource.Dimension.keyboard_key_gap = global::Sample.Resource.Dimension.keyboard_key_gap;
			global::Sino.Keyboard.Droid.Resource.Dimension.keyboard_key_height = global::Sample.Resource.Dimension.keyboard_key_height;
			global::Sino.Keyboard.Droid.Resource.Dimension.keyboard_key_radius = global::Sample.Resource.Dimension.keyboard_key_radius;
			global::Sino.Keyboard.Droid.Resource.Drawable.keyboard_bg_key = global::Sample.Resource.Drawable.keyboard_bg_key;
			global::Sino.Keyboard.Droid.Resource.Drawable.keyboard_bg_number = global::Sample.Resource.Drawable.keyboard_bg_number;
			global::Sino.Keyboard.Droid.Resource.Drawable.keyboard_key_bg_normal = global::Sample.Resource.Drawable.keyboard_key_bg_normal;
			global::Sino.Keyboard.Droid.Resource.Drawable.keyboard_key_bg_pressed = global::Sample.Resource.Drawable.keyboard_key_bg_pressed;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_commit = global::Sample.Resource.Id.keyboard_commit;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_0 = global::Sample.Resource.Id.keyboard_number_0;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_1 = global::Sample.Resource.Id.keyboard_number_1;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_2 = global::Sample.Resource.Id.keyboard_number_2;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_3 = global::Sample.Resource.Id.keyboard_number_3;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_4 = global::Sample.Resource.Id.keyboard_number_4;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_5 = global::Sample.Resource.Id.keyboard_number_5;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_number_6 = global::Sample.Resource.Id.keyboard_number_6;
			global::Sino.Keyboard.Droid.Resource.Id.keyboard_view = global::Sample.Resource.Id.keyboard_view;
			global::Sino.Keyboard.Droid.Resource.Layout.keyboard_vehicle_plate = global::Sample.Resource.Layout.keyboard_vehicle_plate;
			global::Sino.Keyboard.Droid.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::Sino.Keyboard.Droid.Resource.String.Hello = global::Sample.Resource.String.Hello;
			global::Sino.Keyboard.Droid.Resource.Style.KeyboardInputNumber = global::Sample.Resource.Style.KeyboardInputNumber;
			global::Sino.Keyboard.Droid.Resource.Style.KeyboardInputNumber_Password = global::Sample.Resource.Style.KeyboardInputNumber_Password;
			global::Sino.Keyboard.Droid.Resource.Style.keyboard_dialog = global::Sample.Resource.Style.keyboard_dialog;
			global::Sino.Keyboard.Droid.Resource.Xml.keyboard_vehicle_code = global::Sample.Resource.Xml.keyboard_vehicle_code;
			global::Sino.Keyboard.Droid.Resource.Xml.keyboard_vehicle_number = global::Sample.Resource.Xml.keyboard_vehicle_number;
			global::Sino.Keyboard.Droid.Resource.Xml.keyboard_vehicle_number_extra = global::Sample.Resource.Xml.keyboard_vehicle_number_extra;
			global::Sino.Keyboard.Droid.Resource.Xml.keyboard_vehicle_province_0 = global::Sample.Resource.Xml.keyboard_vehicle_province_0;
			global::Sino.Keyboard.Droid.Resource.Xml.keyboard_vehicle_province_1 = global::Sample.Resource.Xml.keyboard_vehicle_province_1;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int keyboard_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int keyboard_key_frontend_color_normal = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int keyboard_key_frontend_color_pressed = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int keyboard_key_text = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int keyboard_key_gap = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int keyboard_key_height = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int keyboard_key_radius = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int keyboard_bg_key = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int keyboard_bg_number = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int keyboard_key_bg_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int keyboard_key_bg_pressed = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int MyButton = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int keyboard_commit = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int keyboard_number_0 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int keyboard_number_1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int keyboard_number_2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int keyboard_number_3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int keyboard_number_4 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int keyboard_number_5 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int keyboard_number_6 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int keyboard_view = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int keyboard_vehicle_plate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int KeyboardInputNumber = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int KeyboardInputNumber_Password = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int keyboard_dialog = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int keyboard_vehicle_code = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int keyboard_vehicle_number = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int keyboard_vehicle_number_extra = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int keyboard_vehicle_province_0 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int keyboard_vehicle_province_1 = 2130968580;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
